apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started
spec:
  selector:
    matchLabels:
      app: getting-started
  template:
    metadata:
      labels:
        app: getting-started
    spec:
      containers:
      - name: getting-started
        image: nidhinmetocean/getting-started:v2.0.0
